In [124]:
import yfinance as yf
import pandas as pd
import numpy as np

In [125]:
def daily_return(data):
  curr = data['Close']
  prev = data['Open']
  ret = (curr - prev)/prev
  return ret

In [126]:
def cumu_return(data):  #cumulative returns
  curr = data['Close'][-1]
  prev = data['Open'][0]
  return (curr-prev)/prev

In [127]:
def MDD(data):  #Maximum Drawdown
  data = data['Close']
  max = data[0]
  min = -np.Inf
  dd = 0
  mdd = 0
  for i in range(len(data)-1):
    if data[i] < data[i+1]:
      max = data[i+1]
      min = -np.Inf
    if data[i] > data[i+1]:
      min = data[i+1]
      dd = (min-max)/max
    if mdd>dd:
      mdd=dd
  return mdd

In [128]:
def sharpe(data,riskrate): #Sharpe Ratio
  returns = np.diff(data['Close']) / data['Close'][:-1]
  excessreturns = returns - riskrate
  average_excessreturns = np.mean(excessreturns)
  standard_deviation = np.std(returns)
  sharpe_ratio = average_excessreturns / standard_deviation
  
  return sharpe_ratio

In [129]:
def volatility(data): #Volatility
    returns = np.log(data['Close'] / np.roll(data['Close'], 1))
    returns = returns[1:]
    volatility = np.std(returns)
    
    return volatility*(len(data)**0.5)

In [138]:
def sortino(data,riskrate): #Sortino
  returns = np.diff(data['Close']) / data['Close'][:-1]
  excessreturns = returns - riskrate
  average_excessreturns = np.mean(excessreturns)
  returns = returns[returns<0]
  standard_deviation = np.std(returns)
  sortino_ratio = average_excessreturns / standard_deviation

  return sortino_ratio

In [161]:
equity_list=['RELIANCE.NS','TATAPOWER.NS','ADANIPORTS.NS','AUROPHARMA.NS','SBIN.NS']
index_list=['Cumulative Return', 'MDD', 'Sharpe Ratio', 'Volatility', 'Sortino']
table1 = pd.DataFrame(index=index_list)
for eq in equity_list:
  ticker = yf.Ticker(eq)
  df = ticker.history(interval='1d', start = '2010-01-01', end = '2023-05-01')
  table1[eq] = [cumu_return(df), MDD(df), sharpe(df,0.0), volatility(df), sortino(df,0.0)]

In [162]:
table1

,RELIANCE.NS,TATAPOWER.NS,ADANIPORTS.NS,AUROPHARMA.NS,SBIN.NS
Cumulative Return,3.941655,0.938637,5.603973,6.442652,1.919095
MDD,-0.170309,-0.190291,-0.263715,-0.360873,-0.263085
Sharpe Ratio,0.036505,0.020065,0.035757,0.036715,0.025737
Volatility,1.015020,1.235676,1.406236,1.441059,1.218689
Sortino,0.056515,0.029973,0.050708,0.053960,0.040112

In [168]:
indices = ['^NDX', '^IXCO', '^SOX', '^SPX', '^RUT']
index_list = ['Cumulative Return', 'MDD', 'Sharpe Ratio', 'Volatility', 'Sortino']
table2 = pd.DataFrame(index=index_list)
for i in indices:
  ticker = yf.Ticker(i)
  df = ticker.history(interval='1d', start = '2010-01-01', end = '2023-05-01')
  table2[i] = [cumu_return(df), MDD(df), sharpe(df,0.0), volatility(df), sortino(df,0.02)]

In [170]:
table2

                       ^NDX     ^IXCO      ^SOX      ^SPX      ^RUT
Cumulative Return  6.035673  7.389266  7.231469  2.734219  1.816370
MDD               -0.132416 -0.136944 -0.159608 -0.139333 -0.168754
Sharpe Ratio       0.050594  0.050675  0.043484  0.040370  0.028223
Volatility         0.767825  0.847558  1.060718  0.649783  0.842882
Sortino           -1.866763 -1.719979 -1.464106 -2.139746 -1.763801