In [19]:
import yfinance as yf
import numpy as np
import pandas as pd

In [20]:
ticker_symbols = ['AAPL', 'GOOGL', 'MSFT', 'AMZN', 'AAL','HSI','BSE.NS','DJI','RUT','NYA']

In [21]:
data = yf.download(ticker_symbols, start='2010-01-01', end='2023-01-01')

[*********************100%***********************]  10 of 10 completed

In [22]:
data

            Adj Close                                                   \
                  AAL        AAPL       AMZN      BSE.NS           DJI
Date
2010-01-04   4.496876    6.496294   6.695000         NaN  10584.000000
2010-01-05   5.005957    6.507527   6.734500         NaN  10572.000000
2010-01-06   4.798554    6.404016   6.612500         NaN  10573.700195
2010-01-07   4.939965    6.392175   6.500000         NaN  10606.900391
2010-01-08   4.845691    6.434672   6.676000         NaN  10618.200195
...               ...         ...        ...         ...           ...
2022-12-26        NaN         NaN        NaN  534.049988           NaN
2022-12-27  12.530000  129.652435  83.040001  537.900024           NaN
2022-12-28  12.320000  125.674019  81.820000  538.000000           NaN
2022-12-29  12.700000  129.233658  84.180000  535.950012           NaN
2022-12-30  12.720000  129.552719  84.000000  544.900024           NaN

                                                                  ...  \
                GOOGL           HSI        MSFT          NYA RUT  ...
Date                                                              ...
2010-01-04  15.684434      1.210000   23.623899  7326.740234 NaN  ...
2010-01-05  15.615365  22279.599609   23.631527  7354.870117 NaN  ...
2010-01-06  15.221722  22416.699219   23.486504  7377.700195 NaN  ...
2010-01-07  14.867367      1.210000   23.242256  7393.930176 NaN  ...
2010-01-08  15.065566  22296.800781   23.402544  7425.350098 NaN  ...
...               ...           ...         ...          ...  ..  ...
2022-12-26        NaN           NaN         NaN          NaN NaN  ...
2022-12-27  87.389999           NaN  236.367981          NaN NaN  ...
2022-12-28  86.019997           NaN  233.944031          NaN NaN  ...
2022-12-29  88.449997           NaN  240.407837          NaN NaN  ...
2022-12-30  88.230003           NaN  239.220825          NaN NaN  ...

                Volume                                                        \
                   AAL         AAPL         AMZN    BSE.NS  DJI        GOOGL
Date
2010-01-04   9837300.0  493729600.0  151998000.0       NaN  0.0   78169752.0
2010-01-05  25212000.0  601904800.0  177038000.0       NaN  0.0  120067812.0
2010-01-06  16597900.0  552160000.0  143576000.0       NaN  0.0  158988852.0
2010-01-07  14033400.0  477131200.0  220604000.0       NaN  0.0  256315428.0
2010-01-08  12760000.0  447610800.0  196610000.0       NaN  0.0  188783028.0
...                ...          ...          ...       ...  ...          ...
2022-12-26         NaN          NaN          NaN  495849.0  NaN          NaN
2022-12-27  18878200.0   69007800.0   57284000.0  367471.0  NaN   20097300.0
2022-12-28  20470400.0   85438400.0   58228600.0  386750.0  NaN   19523200.0
2022-12-29  19706300.0   75703700.0   54995900.0  252944.0  NaN   23333500.0
2022-12-30  19002800.0   77034200.0   62401200.0  397830.0  NaN   23986300.0


                HSI        MSFT  NYA RUT
Date
2010-01-04   6381.0  38409100.0  0.0 NaN
2010-01-05      0.0  49749600.0  0.0 NaN
2010-01-06      0.0  58182400.0  0.0 NaN
2010-01-07  11104.0  50559700.0  0.0 NaN
2010-01-08      0.0  51197400.0  0.0 NaN
...             ...         ...  ...  ..
2022-12-26      NaN         NaN  NaN NaN
2022-12-27      NaN  16688600.0  NaN NaN
2022-12-28      NaN  17457100.0  NaN NaN
2022-12-29      NaN  19770700.0  NaN NaN
2022-12-30      NaN  21938500.0  NaN NaN

[3315 rows x 60 columns]

In [23]:
md=data

In [24]:
# mdd

In [25]:
data=data['Adj Close']

In [26]:
cum_return = (data.iloc[-1] - data.iloc[0]) / data.iloc[0]
cum_return

AAL        1.828630
AAPL      18.942559
AMZN      11.546676
BSE.NS          NaN
DJI             NaN
GOOGL      4.625323
HSI             NaN
MSFT       9.126221
NYA             NaN
RUT             NaN
dtype: float64

In [27]:
def std_dev(data):
    # Get number of observations
    n = len(data)
    # Calculate mean
    mean = sum(data) / n
    # Calculate deviations from the mean
    deviations = sum([(x - mean)**2 for x in data])
    # Calculate Variance & Standard Deviation
    variance = deviations / (n - 1)
    s = variance**(1/2)
    return s

In [28]:
data
len(data)

3315

In [29]:
data

,AAL,AAPL,AMZN,BSE.NS,DJI,GOOGL,HSI,MSFT,NYA,RUT
Date,,,,,,,,,,
2010-01-04,4.496876,6.496294,6.695000,NaN,10584.000000,15.684434,1.210000,23.623899,7326.740234,NaN
2010-01-05,5.005957,6.507527,6.734500,NaN,10572.000000,15.615365,22279.599609,23.631527,7354.870117,NaN
2010-01-06,4.798554,6.404016,6.612500,NaN,10573.700195,15.221722,22416.699219,23.486504,7377.700195,NaN
2010-01-07,4.939965,6.392175,6.500000,NaN,10606.900391,14.867367,1.210000,23.242256,7393.930176,NaN
2010-01-08,4.845691,6.434672,6.676000,NaN,10618.200195,15.065566,22296.800781,23.402544,7425.350098,NaN
...,...,...,...,...,...,...,...,...,...,...
2022-12-26,NaN,NaN,NaN,534.049988,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-27,12.530000,129.652435,83.040001,537.900024,NaN,87.389999,NaN,236.367981,NaN,NaN
2022-12-28,12.320000,125.674019,81.820000,538.000000,NaN,86.019997,NaN,233.944031,NaN,NaN
2022-12-29,12.700000,129.233658,84.180000,535.950012,NaN,88.449997,NaN,240.407837,NaN,NaN
2022-12-30,12.720000,129.552719,84.000000,544.900024,NaN,88.230003,NaN,239.220825,NaN,NaN

In [30]:
def sharpe_ratio(return_series, N, rf):
    mean = return_series.mean() * N -rf
    sigma = return_series.std() * np.sqrt(N)
    return mean / sigma

N = 255 #255 trading days in a year
rf =1.4 #1% risk free rate
sharpes = data.apply(sharpe_ratio, args=(N,rf,),axis=0)

sharpes

AAL       28.150623
AAPL      16.518229
AMZN      17.396249
BSE.NS    31.638184
DJI       44.312317
GOOGL     21.925871
HSI       25.848555
MSFT      17.051572
NYA       65.671391
RUT       45.686381
dtype: float64

In [31]:
def vola(return_series, N, rf):
  return return_series.std() * np.sqrt(N)

In [32]:
N = 255 #255 trading days in a year
rf =0.01 #1% risk free rate
vola = data.apply(vola, args=(N,rf,),axis=0)

In [33]:
vola

AAL          228.590477
AAPL         761.470204
AMZN         863.565122
BSE.NS      5072.891464
DJI       112230.592352
GOOGL        571.745536
HSI       165901.394573
MSFT        1422.057028
NYA        41882.365481
RUT            6.822083
dtype: float64

In [48]:
adj_close_prices = data['Adj Close']

In [49]:
#data = yf.download(ticker_symbols, start='2010-01-01', end='2023-01-01')

def calculate_max_drawdown(prices):
    cumulative_returns = prices / prices.iloc[0]
    previous_peaks = cumulative_returns.cummax()
    drawdowns = cumulative_returns - previous_peaks
    max_drawdown = drawdowns.min()
    return max_drawdown

# Calculate maximum drawdown for each equity
max_drawdowns = adj_close_prices.apply(calculate_max_drawdown, axis=0)

# Display the maximum drawdown for each equity
print(max_drawdowns)

AAL         -10.662674
AAPL         -8.429463
AMZN        -15.646078
BSE.NS             NaN
DJI          -1.035478
GOOGL        -4.234039
HSI      -27400.021089
MSFT         -5.331948
NYA          -0.737821
RUT                NaN
dtype: float64

In [50]:
def calculate_sortino_ratio(prices, risk_free_rate=0.0):
    returns = prices.pct_change().dropna()
    downside_returns = np.where(returns < risk_free_rate, returns, 0)
    downside_deviation = np.std(downside_returns)
    
    expected_return = np.mean(returns)
    sortino_ratio = (expected_return - risk_free_rate) / downside_deviation
    return sortino_ratio

# Calculate Sortino ratio for each equity
sortino_ratios = adj_close_prices.apply(calculate_sortino_ratio, risk_free_rate=0.02)

# Display the Sortino ratio for each equity
print(sortino_ratios)

AAL          -0.915940
AAPL         -1.383277
AMZN         -1.270271
BSE.NS       -0.689218
DJI          -2.225339
GOOGL        -1.490187
HSI       30887.089063
MSFT         -1.533072
NYA          -2.184419
RUT          -1.827003
dtype: float64

In [51]:
# import yfinance as yf
# import pandas as pd

In [52]:
# def get_historical_data(ticker, start_date):
#     # Pull Historical Data
#     data = yf.download(ticker, start=start_date)
#     # Calculate Daily Returns
#     data['Daily Return'] = data['Adj Close'].pct_change()   
#     return data.dropna()

In [53]:
# def std_dev(data):
#     # Get number of observations
#     n = len(data)
#     # Calculate mean
#     mean = sum(data) / n
#     # Calculate deviations from the mean
#     deviations = sum([(x - mean)**2 for x in data])
#     # Calculate Variance & Standard Deviation
#     variance = deviations / (n - 1)
#     s = variance**(1/2)
#     return s

In [54]:
# def sharpe_ratio(data, risk_free_rate=0.0):
#     # Calculate Average Daily Return
#     mean_daily_return = sum(data) / len(data)
#     # Calculate Standard Deviation
#     s = std_dev(data)
#     # Calculate Daily Sharpe Ratio
#     daily_sharpe_ratio = (mean_daily_return - risk_free_rate) / s
#     # Annualize Daily Sharpe Ratio
#     sharpe_ratio = 252**(1/2) * daily_sharpe_ratio
    
#     return sharpe_ratio

In [55]:
# AAPL=get_historical_data('AAPL',start_date='2010-01-01')

In [56]:
# sharpe_ratio(AAPL['Daily Return'])

In [57]:
# import pandas_datareader.data as web
# import datetime as dt
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# plt.style.use('ggplot')


# start = dt.datetime(2013, 1, 1)
# end = dt.datetime(2020, 10, 1)

# tickers = ['AAPL', 'AMZN', 'MSFT', 'GOOGL','FB']

# stocks = web.DataReader(tickers,'yahoo', start, end )

# stocks.head()